Repository gaj23/face-it, pull requests merged in 2021-02, with the labels that each got.

#8 Ch/feature/footer
  .gitignore
  package-lock.json
  package.json
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  src/Data/makeUp.json
  src/components/App/App.css
  src/components/App/App.js
  src/components/Category/Category.css
  src/components/Category/Category.js
  src/components/Details/Details.css
  src/components/Details/Details.js
  src/components/Footer/Footer.css
  src/components/Footer/Footer.js
  src/components/Form/Form.css
  src/components/Form/Form.js
  src/components/Item/Item.css
  src/components/Item/Item.js
  src/components/Logo/Logo.css
  src/components/Logo/Logo.js
  src/components/Nav/Nav.css
  src/components/Nav/Nav.js
  src/components/Types/Types.css
  src/components/Types/Types.js
  src/index.css
  src/index.js
Labels: enhancement

#9 Implement Footer component and Logo
  src/components/App/App.js
  src/components/Footer/Footer.css
  src/components/Footer/Footer.js
  src/components/Logo/Logo.css
  src/components/Logo/Logo.js
Labels: MVP, enhancement

#20 Gaj/feature/error components
  src/components/App/App.css
  src/components/App/App.js
  src/components/Category/AllergenFriendly.js
  src/components/Category/Eco.js
  src/components/Category/Vegan.js
  src/components/Error/Error.css
  src/components/Error/Error.js
  src/components/Error/error-img.jpg
  src/index.js
Labels: MVP, enhancement

#23 Loading Message Component
  src/components/App/App.js
  src/components/Loading/Loading.css
  src/components/Loading/Loading.js
  src/components/LoadingImg/LoadingImg.css
  src/components/LoadingImg/LoadingImg.js
Labels: MVP, enhancement, refactor
