Repository gaj23/face-it, pull requests merged in 2021-03, with the labels that each got.

#28 Ch/feature/category descriptions
  src/components/Category/AllergenFriendly.js
  src/components/Category/Category.css
  src/components/Category/Eco.js
  src/components/Category/Vegan.js
Labels: MVP, enhancement

#29 Ch/feature/form component
  src/components/App/App.css
  src/components/App/App.js
  src/components/Cosmetic/Cosmetic.css
  src/components/Details/Details.css
  src/components/Details/Details.js
  src/components/Form/Form.css
  src/components/Form/Form.js
  src/components/SearchResult/SearchResult.css
  src/components/SearchResult/SearchResult.js
  src/components/SearchResults/SearchResults.css
  src/components/SearchResults/SearchResults.js
  src/components/SingleProduct/SingleProduct.css
  src/components/SingleProduct/SingleProduct.js
Labels: MVP, enhancement, refactor

#36 Gaj/testing/search bar
  README.md
  cypress.json
  cypress/fixtures/mock.json
  cypress/integration/face_it_spec.js
  cypress/plugins/index.js
  cypress/support/commands.js
  cypress/support/index.js
  package-lock.json
  package.json
  src/components/Footer/Footer.css
  src/components/Footer/Footer.js
  src/components/Footer/github-logo.png
  src/components/Footer/linkedin-logo.png
  src/components/Footer/twitter-logo.png
  src/components/Type/Type.js
Labels: MVP, enhancement

#37 Unregister service worker to download
  src/index.js
Labels: MVP, enhancement

#40 Gaj/fix/capitalization
  src/Components/App/App.css
  src/Components/App/App.js
  src/Components/Category/AllergenFriendly.js
  src/Components/Category/Category.css
  src/Components/Category/Category.js
  src/Components/Category/Eco.js
  src/Components/Category/Vegan.js
  src/Components/Cosmetic/Cosmetic.css
  src/Components/Cosmetic/Cosmetic.js
  src/Components/Details/Details.css
  src/Components/Details/Details.js
  src/Components/Error/Error.css
  src/Components/Error/Error.js
  src/Components/Error/error-img.jpg
  src/Components/Footer/Footer.css
  src/Components/Footer/Footer.js
  src/Components/Footer/github-logo.png
  src/Components/Footer/linkedin-logo.png
  src/Components/Footer/twitter-logo.png
  src/Components/Form/Form.css
  src/Components/Form/Form.js
  src/Components/Items/Items.css
  src/Components/Items/Items.js
  src/Components/Loading/Loading.css
  src/Components/Loading/Loading.js
  src/Components/LoadingImg/LoadingImg.css
  src/Components/LoadingImg/LoadingImg.js
  src/Components/Logo/Logo.css
  src/Components/Logo/Logo.js
  src/Components/Nav/Nav.css
  src/Components/Nav/Nav.js
  src/Components/SearchResult/SearchResult.css
  src/Components/SearchResult/SearchResult.js
  src/Components/SearchResults/SearchResults.css
  src/Components/SearchResults/SearchResults.js
  src/Components/SingleProduct/SingleProduct.css
  src/Components/SingleProduct/SingleProduct.js
  src/Components/Type/Type.css
  src/Components/Type/Type.js
Labels: MVP, bug, refactor

#43 Ch/feature/refactor
  src/Components/App/App.css
  src/Components/App/App.js
  src/Components/Category/Category.js
  src/Components/Cosmetic/Cosmetic.css
  src/Components/Error/Error.css
  src/Components/Footer/Footer.css
  src/Components/Footer/Footer.js
  src/Components/Form/Form.js
  src/Components/Items/Items.js
  src/Components/Loading/Loading.css
  src/Components/Loading/Loading.js
  src/Components/LoadingImg/LoadingImg.css
  src/Components/Nav/Nav.css
  src/Components/SearchResult/SearchResult.css
  src/Components/SearchResult/SearchResult.js
  src/Components/SearchResults/SearchResults.css
  src/Components/SearchResults/SearchResults.js
  src/Components/SingleProduct/SingleProduct.css
  src/Components/Type/Type.css
  src/Components/Type/Type.js
Labels: MVP, bug, enhancement, refactor

#45 Refactor svg attributes
  src/Components/LoadingImg/LoadingImg.js
  src/Components/Logo/Logo.js
Labels: refactor

#46 Kby feature error handling
  src/Components/App/App.css
  src/Components/App/App.js
  src/Components/Category/AllergenFriendly.js
  src/Components/Category/Category.css
  src/Components/Category/Category.js
  src/Components/Category/Eco.js
  src/Components/Category/Vegan.js
  src/Components/Cosmetic/Cosmetic.js
  src/Components/Details/Details.css
  src/Components/Details/Details.js
  src/Components/Error/Error.css
  src/Components/Footer/Footer.css
  src/Components/Footer/Footer.js
  src/Components/Form/Form.css
  src/Components/Form/Form.js
  src/Components/Items/Items.js
  src/Components/Loading/Loading.css
  src/Components/LoadingImg/LoadingImg.css
  src/Components/LoadingImg/LoadingImg.js
  src/Components/Logo/Logo.css
  src/Components/Logo/Logo.js
  src/Components/Nav/Nav.css
  src/Components/Nav/Nav.js
  src/Components/SearchResult/SearchResult.css
  src/Components/SearchResult/SearchResult.js
  src/Components/SearchResults/SearchResults.css
  src/Components/SearchResults/SearchResults.js
  src/Components/SingleProduct/SingleProduct.css
  src/Components/SingleProduct/SingleProduct.js
  src/Components/Type/Type.css
  src/Components/Type/Type.js
  src/index.js
  src/service-worker.js
  src/serviceWorkerRegistration.js
Labels: MVP, refactor

#47 Refactor for Bug Fixes and Media Queries
  src/Components/Category/Category.css
  src/Components/Details/Details.css
  src/Components/Details/Details.js
  src/Components/Items/Items.css
Labels: MVP, enhancement, refactor

#48 Gaj/documentation/update 03 02
  README.md
  cypress.json
  cypress/integration/face_it_spec.js
  src/Components/App/App.js
  src/apiCalls.js
Labels: MVP, testing

#49 Ch/feature/refactor/fix-svg
  src/Components/LoadingImg/LoadingImg.js
  src/Components/Logo/Logo.js
  src/Components/Nav/Nav.css
  src/Components/Nav/Nav.js
Labels: enhancement, testing

#51 Ch/feature/refactor router
  src/Components/App/App.js
  src/Components/SingleProduct/SingleProduct.js
Labels: refactor
